apiVersion: migration.openshift.io/v1alpha1
kind: MigrationController
metadata:
  name: migration-controller
  namespace: openshift-migration
spec:
  azure_resource_group: ''
  cluster_name: host
  migration_velero: true
  migration_controller: false
  migration_ui: false
  migration_log_reader: true
  restic_timeout: 1h
