---
- name: Prepare
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Create namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
