apiVersion: migration.openshift.io/v1alpha1
kind: MigrationController
metadata:
  name: migrationcontroller
spec:
  cluster_name: host
  migration_velero: true
  migration_controller: true
  migration_ui: true
  migration_log_reader: true
