apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: migrationtenants.migration.openshift.io
spec:
  group: migration.openshift.io
  names:
    kind: MigrationTenant
    listKind: MigrationTenantList
    plural: migrationtenants
    singular: migrationtenant
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
