apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: rh-verified-applications
  namespace: openshift-marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: rh-verified-operators
  authorizationToken:
    secretName: marketplacesecret

