- hosts: localhost
  vars_prompt:
  - name: release
    prompt: "Release"
    private: no

  - name: channel
    prompt: "Channel"
    private: no

  tasks:
  - name: Replace operator tags in CSV
    replace:
      path:  "{{ playbook_dir }}/../deploy/olm-catalog/bundle/manifests/crane-operator.v99.0.0.clusterserviceversion.yaml"
      regexp: ':latest'
      replace: ":release-{{ release }}"

  tasks:
  - name: Replace operator tags in molecule test
    replace:
      path:  "{{ playbook_dir }}/../molecule/test-local/converge.yml"
      regexp: ':latest'
      replace: ":release-{{ release }}"

  - name: Replace operand in CSV
    replace:
      path:  "{{ playbook_dir }}/../deploy/olm-catalog/bundle/manifests/crane-operator.v99.0.0.clusterserviceversion.yaml"
      regexp: 'value: latest'
      replace: "value: release-{{ release }}"

  - name: Fix the version in the CSV
    replace:
      path:  "{{ playbook_dir }}/../deploy/olm-catalog/bundle/manifests/crane-operator.v99.0.0.clusterserviceversion.yaml"
      regexp: '99\.0\.0'
      replace: "{{ release }}"

  - name: Move CSV
    shell: |
           git mv \
           {{ playbook_dir }}/../deploy/olm-catalog/bundle/manifests/crane-operator.v99.0.0.clusterserviceversion.yaml \
           {{ playbook_dir }}/../deploy/olm-catalog/bundle/manifests/crane-operator.v{{ release }}.clusterserviceversion.yaml 

  - name: Replace operator tags in operator.yml
    replace:
      path:  "{{ playbook_dir }}/../deploy/non-olm/operator.yml"
      regexp: ':latest'
      replace: ":release-{{ release }}"

  - name: Replace operand in operator.yml
    replace:
      path:  "{{ playbook_dir }}/../deploy/non-olm/operator.yml"
      regexp: 'value: latest'
      replace: "value: release-{{ release }}"

  - name: Replace default channel in annotations
    replace:
      path:  "{{ playbook_dir }}/../deploy/olm-catalog/bundle/metadata/annotations.yaml"
      regexp: 'operators.operatorframework.io.bundle.channel.default.v1:.*'
      replace: "operators.operatorframework.io.bundle.channel.default.v1: {{ channel }}"

  - name: Replace channel list in annotations
    replace:
      path:  "{{ playbook_dir }}/../deploy/olm-catalog/bundle/metadata/annotations.yaml"
      regexp: 'operators.operatorframework.io.bundle.channels.v1:.*'
      replace: "operators.operatorframework.io.bundle.channels.v1: {{ channel }}"

  - name: Replace default channel in dockerfile
    replace:
      path:  "{{ playbook_dir }}/../build/Dockerfile.bundle"
      regexp: 'LABEL operators.operatorframework.io.bundle.channel.default.v1=.*'
      replace: "LABEL operators.operatorframework.io.bundle.channel.default.v1={{ channel }}"

  - name: Replace channel list in dockerfile
    replace:
      path:  "{{ playbook_dir }}/../build/Dockerfile.bundle"
      regexp: 'LABEL operators.operatorframework.io.bundle.channels.v1=.*'
      replace: "LABEL operators.operatorframework.io.bundle.channels.v1={{ channel }}"

  - name: Replace version in defaults/main.yml
    replace:
      path: "{{ playbook_dir }}/../roles/migrationcontroller/defaults/main.yml"
      regexp: 'mig_operator_version:.*'
      replace: "mig_operator_version: \"{{ release }}\""
