---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -d "{extends: relaxed, rules: {line-length: {max: 400}}}" roles
platforms:
  - name: kind
    groups:
      - k8s
    image: bsycorp/kind:${KUBE_VERSION:-latest-1.19}
    privileged: true
    override_command: false
    exposed_ports:
      - 8443/tcp
      - 10080/tcp
    published_ports:
      - 0.0.0.0:${TEST_CLUSTER_PORT:-10443}:8443/tcp
    pre_build_image: true
    volumes:
      - ${MOLECULE_PROJECT_DIRECTORY}:/build:Z
provisioner:
  name: ansible
  log: true
  lint: |
    set -e
    ansible-lint
  inventory:
    group_vars:
      all:
        controller_namespace: ${TEST_CONTROLLER_NAMESPACE:-openshift-migration}
        migration_namespace: ${TEST_MIGRATION_NAMESPACE:-openshift-migration}
        namespace: ${TEST_OPERATOR_NAMESPACE:-openshift-migration}
        kubeconfig_file: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
        test_image: ${REPLACE_IMAGE:-quay.io/konveyor/mig-operator-container:release-1.5.1}
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        template_dir: ${MOLECULE_PROJECT_DIRECTORY}/molecule/templates
        deploy_dir: ${MOLECULE_PROJECT_DIRECTORY}/molecule/deploy
  env:
    K8S_AUTH_KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    KUBECONFIG: ${MOLECULE_EPHEMERAL_DIRECTORY}/kubeconfig
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
    KIND_PORT: '${TEST_CLUSTER_PORT:-10443}'
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
scenario:
  name: kind
  test_sequence:
    - lint
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
