---
- name: Prepare
  hosts: k8s
  gather_facts: no
  tasks:
    - name: Fetch the kubeconfig
      fetch:
        dest: '{{ kubeconfig_file }}'
        flat: yes
        src: /root/.kube/config

    - name: Change the kubeconfig server/port to the proper value
      replace:
        regexp: 'https://.*:8443'
        replace: "https://localhost:{{ lookup('env', 'KIND_PORT') }}"
        path: '{{ kubeconfig_file }}'
      delegate_to: localhost

    - name: Wait for the Kubernetes API to become available (this could take a minute)
      uri:
        url: "http://localhost:10080/kubernetes-ready"
        status_code: 200
        validate_certs: no
      register: result
      until: (result.status|default(-1)) == 200
      retries: 60
      delay: 5

- name: Prepare
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Create Custom Resource Definitions
      k8s:
        definition: "{{ lookup('file', item) }}"
      with_items:
      - "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy/olm-catalog/bundle/manifests/migrationcontroller.crd.yaml"

    - name: Create namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
