apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: migmigrations.migration.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=='Ready')].status
    name: Ready
    type: string
  - JSONPath: .spec.migPlanRef.name
    name: Plan
    type: string
  - JSONPath: .spec.stage
    name: Stage
    type: string
  - JSONPath: .spec.rollback
    name: Rollback
    type: string
  - JSONPath: .status.itinerary
    name: Itinerary
    type: string
  - JSONPath: .status.phase
    name: Phase
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: migration.openshift.io
  names:
    kind: MigMigration
    plural: migmigrations
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            canceled:
              type: boolean
            keepAnnotations:
              type: boolean
            migPlanRef:
              type: object
            quiescePods:
              type: boolean
            rollback:
              type: boolean
            stage:
              type: boolean
            verify:
              type: boolean
          required:
          - stage
          type: object
        status:
          properties:
            pipeline:
              type: array
              items:
                type: object
                properties:
                  message:
                    type: string
                  name:
                    type: string
                  phase:
                    type: string
                  completed:
                    type: string
                    format: date-time
                  started:
                    type: string
                    format: date-time
                  failed:
                    type: boolean
                  progress:
                    type: array
                    items:
                      type: string
            errors:
              items:
                type: string
              type: array
            itinerary:
              type: string
            observedDigest:
              type: string
            phase:
              type: string
            startTimestamp:
              format: date-time
              type: string
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
