apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: migplans.migration.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type=='Ready')].status
    name: Ready
    type: string
  - JSONPath: .spec.srcMigClusterRef.name
    name: Source
    type: string
  - JSONPath: .spec.destMigClusterRef.name
    name: Target
    type: string
  - JSONPath: .spec.migStorageRef.name
    name: Storage
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: migration.openshift.io
  names:
    kind: MigPlan
    plural: migplans
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            closed:
              type: boolean
            destMigClusterRef:
              type: object
            hooks:
              items:
                properties:
                  executionNamespace:
                    type: string
                  phase:
                    type: string
                  reference:
                    type: object
                  serviceAccount:
                    type: string
                required:
                - reference
                - phase
                - executionNamespace
                - serviceAccount
                type: object
              type: array
            indirectImageMigration:
              type: boolean
            indirectVolumeMigration:
              type: boolean
            migStorageRef:
              type: object
            namespaces:
              items:
                type: string
              type: array
            persistentVolumes:
              items:
                properties:
                  capacity:
                    type: string
                  name:
                    type: string
                  pvc:
                    properties:
                      accessModes:
                        items:
                          type: string
                        type: array
                      hasReference:
                        type: boolean
                      name:
                        type: string
                      namespace:
                        type: string
                    type: object
                  selection:
                    properties:
                      accessMode:
                        type: string
                      action:
                        type: string
                      copyMethod:
                        type: string
                      storageClass:
                        type: string
                      verify:
                        type: boolean
                    type: object
                  storageClass:
                    type: string
                  supported:
                    properties:
                      actions:
                        items:
                          type: string
                        type: array
                      copyMethods:
                        items:
                          type: string
                        type: array
                    required:
                    - actions
                    - copyMethods
                    type: object
                required:
                - supported
                - selection
                type: object
              type: array
            refresh:
              type: boolean
            srcMigClusterRef:
              type: object
          type: object
        status:
          properties:
            destStorageClasses:
              items:
                properties:
                  accessModes:
                    items:
                      type: string
                    type: array
                  default:
                    type: boolean
                  name:
                    type: string
                  provisioner:
                    type: string
                type: object
              type: array
            excludedResources:
              items:
                type: string
              type: array
            incompatibleNamespaces:
              items:
                properties:
                  gvks:
                    items:
                      properties:
                        group:
                          type: string
                        kind:
                          type: string
                        version:
                          type: string
                      required:
                      - group
                      - version
                      - kind
                      type: object
                    type: array
                  name:
                    type: string
                required:
                - name
                - gvks
                type: object
              type: array
            observedDigest:
              type: string
            srcStorageClasses:
              items:
                properties:
                  accessModes:
                    items:
                      type: string
                    type: array
                  default:
                    type: boolean
                  name:
                    type: string
                  provisioner:
                    type: string
                type: object
              type: array
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
